name: stroll_task_2
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  record: ^5.0.5
  just_audio: ^0.9.38
  permission_handler: ^11.3.1
  path_provider: ^2.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true


  assets:
    - assets/
    - assets/images/

  fonts:
    - family: ProximaNova
      fonts:
        - asset: fonts/ProximaNova-Regular.otf
        - asset: fonts/proximanova-medium.otf
          weight: 500
        - asset: fonts/Proxima Nova Semibold.otf
          weight: 600
        - asset: fonts/Proxima Nova Alt Bold.otf
          weight: 700
